In [1]:
import os
databricks = "DATABRICKS_RUNTIME_VERSION" in os.environ

### Initialize Local

In [2]:
if not databricks:
        
    # Set up environment variables (optional, but sometimes needed)
    os.environ["PYSPARK_PYTHON"] = "python3"
    os.environ["JAVA_HOME"] = os.environ["CONDA_PREFIX"]
    
    from pyspark.sql import SparkSession
    
    # Initialize a Spark session
    spark = SparkSession.builder \
    .appName("LocalPySpark") \
    .master("local[*]") \
    .config("spark.driver.memory", "4g") \
    .config("spark.sql.execution.arrow.enabled", "true") \
    .config("spark.driver.host", "127.0.0.1") \
    .config("spark.driver.bindAddress", "127.0.0.1") \
    .getOrCreate()

25/03/25 23:31:35 WARN Utils: Your hostname, erwin-dekstop resolves to a loopback address: 127.0.1.1; using 192.168.2.165 instead (on interface wlx28ee52bcb21e)
25/03/25 23:31:35 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/erwin/anaconda3/envs/airbnb-demo/lib/python3.10/site-packages/pyspark/jars/spark-unsafe_2.12-3.1.2.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
25/03/25 23:31:40 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
25/03/25 23:31:42 WARN SQLConf: The SQL config 'spark.sql.execution.arrow.enabled' has been deprecated in Spark v3.0 and may be removed in the future. Use 'spark.sql.execution.arrow.pyspark.enabled' instead of it.
25/03/25 23:31:42 WARN SQLConf: The SQL config 'spark.sql.execution.arrow.enabled' has been deprecated in Spark v3.0 and may be removed in the future. Use 'spark.sql.execution.arrow.pyspark.enabled' instead of it.
25/03/25 23:31:42 WARN SQLConf: The SQL config 'spark.sql.execution.arrow.enabled' has been deprecated in Spark v3.0 and may be removed in the future. Use 'spark.sql.execution.arrow.pyspark.enabled' instead of it.

### Initialize Databricks

In [3]:
if databricks:
    dbutils.widgets.text("city", "amsterdam") 
    city = dbutils.widgets.get("city")
    dbutils.widgets.dropdown("train_regression_tree", "false", ["true", "false"], "train regression-tree")
    dbutils.widgets.dropdown("train_neural_network", "false", ["true", "false"], "train neural-network")
    train_regression_tree = dbutils.widgets.get("train_regression_tree").lower() == "true"
    train_neural_network = dbutils.widgets.get("train_neural_network").lower() == "true"
else:
    city = "amsterdam"
    train_regression_tree = True
    train_neural_network = True

### Prepocess

In [4]:
from sentence_transformers import SentenceTransformer
from sklearn.preprocessing import RobustScaler, StandardScaler, MinMaxScaler, OneHotEncoder, MultiLabelBinarizer
from utils import embed, one_hot_encode, multi_hot_encode
import numpy as np
import pandas as pd
import ast

# Load dataset from catalog or csv depending on env
table_name = f"{city}_airbnb_dataset"
if databricks:
    from delta.tables import DeltaTable
    spark_df = spark.read.table(table_name)
    delta_table = DeltaTable.forName(spark, f"workspace.default.{table_name}")
    dataset_version = delta_table.history().select("version").orderBy("version", ascending=False).first()["version"]
else:
    spark_df = spark.read.format("csv") \
            .option("header", "true") \
            .option("inferSchema", "true") \
            .option("sep", ",") \
            .option("escape", '"') \
            .option("encoding", "UTF-8") \
            .option("quote", '"') \
            .option("multiLine", "true") \
            .load(f"{table_name}.csv")
    dataset_version = 1.0
    
df = spark_df.toPandas()
scalers = []
one_hot_encoders = []
multi_hot_encoders = []
ohe_columns = []#["property_type", "room_type"]#["neighbourhood_cleansed", "property_type", "room_type"]
mhe_columns = []#["amenities"]
scale_columns = ["accommodates", "review_scores_value","bathrooms", "availability_365", "bedrooms", "beds"]
other_columns = ["price", "name", "description"]
df = df.drop(columns=[x for x in df.columns if x not in ohe_columns + mhe_columns + scale_columns + other_columns])

example_input = df.head(1).copy()
example_input.columns = example_input.columns.astype(str)
example_input = example_input.drop(columns=["price"])

# Create one-hot-encodings categorical column
for col_name in ohe_columns:
    col = np.array(df[[col_name]])
    encoder = OneHotEncoder()
    encoder.fit(col.reshape(-1, 1))
    df = one_hot_encode(col_name, df, encoder)
    one_hot_encoders.append((col_name, encoder))

# Create multi-hot-encodings for multi-categorical column
for col_name in mhe_columns:
    encoder = MultiLabelBinarizer()
    df[col_name] = df[col_name].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)
    encoder.fit(np.array(df[[col_name]]).flatten())
    df = multi_hot_encode(col_name, df, encoder)
    multi_hot_encoders.append((col_name, encoder))

# Scale columns
df["accommodates"] = df["accommodates"].clip(upper=8)
accommodates_scaler = StandardScaler()
df["accommodates"] = accommodates_scaler.fit_transform(df[["accommodates"]])
scalers.append(("accommodates", accommodates_scaler))

df["review_scores_value"] = df["review_scores_value"].clip(lower=2.5)
reviews_scaler = StandardScaler()
df["review_scores_value"] = reviews_scaler.fit_transform(df[["review_scores_value"]])
scalers.append(("review_scores_value", reviews_scaler))

availability_scaler = StandardScaler()
df["availability_365"] = availability_scaler.fit_transform(df[["availability_365"]])
scalers.append(("availability_365", availability_scaler))

df["bathrooms"] = df["bathrooms"].clip(upper=5)
df["bathrooms"] = df["bathrooms"].clip(upper=5)
bathrooms_scaler = StandardScaler()
df["bathrooms"] = bathrooms_scaler.fit_transform(df[["bathrooms"]])
scalers.append(("bathrooms", bathrooms_scaler))

df["bedrooms"] = df["bedrooms"].clip(upper=7)
bedrooms_scaler = StandardScaler()
df["bedrooms"] = bedrooms_scaler.fit_transform(df[["bedrooms"]])
scalers.append(("bedrooms", bedrooms_scaler))

df["beds"] = df["beds"].clip(upper=10)
beds_scaler = StandardScaler()
df["beds"] = beds_scaler.fit_transform(df[["beds"]])
scalers.append(("beds", beds_scaler))


# Create embeddings
text_columns = ["name", "description"]
embedding_model_path = "sentence-transformers/all-MiniLM-L6-v2"
embedding_model = SentenceTransformer(embedding_model_path)
embedding_df = embed(df, text_columns, embedding_model)
df = df.drop(columns=text_columns)

df.head(100)
df.describe(include='all')

/home/erwin/anaconda3/envs/airbnb-demo/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

,accommodates,bathrooms,bedrooms,beds,availability_365,review_scores_value,price
count,5.869000e+03,5.869000e+03,5.869000e+03,5.869000e+03,5.869000e+03,5.869000e+03,5869.000000
mean,-9.685367e-17,5.690153e-17,-5.326952e-17,-6.537623e-17,-1.694939e-17,-4.824523e-16,256.450843
std,1.000085e+00,1.000085e+00,1.000085e+00,1.000085e+00,1.000085e+00,1.000085e+00,144.132771
min,-1.538266e+00,-2.597249e+00,-1.670066e+00,-1.386682e+00,-1.192500e+00,-7.395010e+00,1.000000
25%,-7.385419e-01,-5.227723e-01,-5.570046e-01,-5.972321e-01,-9.220289e-01,-3.304370e-01,160.000000
50%,-7.385419e-01,-5.227723e-01,-5.570046e-01,-5.972321e-01,-2.965649e-01,8.309900e-02,224.000000
75%,8.609055e-01,5.144659e-01,5.560564e-01,1.922173e-01,9.036497e-01,5.655576e-01,315.000000
max,4.059800e+00,7.775133e+00,6.121361e+00,6.507813e+00,1.892559e+00,1.220323e+00,999.000000

### Create Train/Validation/Test splits

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
import numpy as np

def split_dataset(df: pd.DataFrame):
    target_column = "price"
    x = df.drop(columns=[target_column]).values
    y = df[target_column].values.reshape(-1, 1)  # Reshape for scaler

    # Split into Train (80%) and Temp (20%)
    x_train, x_temp, y_train, y_temp = train_test_split(x, y, test_size=0.2, random_state=42)

    # Split Temp into Validation (10%) and Test (10%)
    x_val, x_test, y_val, y_test = train_test_split(x_temp, y_temp, test_size=0.5, random_state=42)

    # Scale the target using MinMaxScaler fitted only on training data
    y_scaler = MinMaxScaler()
    y_train_scaled = y_scaler.fit_transform(y_train)
    y_val_scaled = y_scaler.transform(y_val)
    y_test_scaled = y_scaler.transform(y_test)

    return x_train, x_val, x_test, y_train_scaled, y_val_scaled, y_test_scaled, y_scaler

x_train, x_val, x_test, y_train, y_val, y_test, y_scaler = split_dataset(df)
x_embedding_train, x_embedding_val, x_embedding_test, _, _, _, _ = split_dataset(embedding_df)

pd.DataFrame(y_train).head(10)

          0
0  0.279559
1  0.165331
2  0.612224
3  0.116232
4  0.374749
5  0.148297
6  0.276553
7  0.259519
8  0.397796
9  0.209419

### Initialize MLFlow Experiments

In [6]:
import mlflow
from mlflow.models import infer_signature
from models import SklearnRegressorPreprocessWrapper, SimpleNNRegressor, TorchNNPreprocessWrapper

if databricks:
    mlflow.tracking._model_registry.utils._get_registry_uri_from_spark_session = lambda: "databricks-uc"
    mlflow.set_tracking_uri("databricks")  # Use Databricks' MLflow tracking
    mlflow.set_experiment("/Users/vanthiel.erwin@gmail.com/airbnb-price-regression")
else:
    dataset_version = 1.0
    mlflow.set_tracking_uri("")
    experiment_name = "airbnb-price-regression"
    if not mlflow.get_experiment_by_name(experiment_name):
        mlflow.create_experiment(experiment_name)
    mlflow.set_experiment(experiment_name)

### Sklearn MLflow runs (without text and description embeddings)

In [7]:
from sklearn.base import BaseEstimator
from datetime import datetime
from sklearn.metrics import mean_absolute_error, r2_score
import urllib.parse
from pathlib import Path
import json

def run_sklearn_regressor(model: BaseEstimator):
    model_type_name = type(model).__name__
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    run_name = f"{model_type_name}_{timestamp}"
    
    with mlflow.start_run(run_name=run_name):
        mlflow.log_param("dataset_version", dataset_version)
          
        # Train Model
        model.fit(x_train, y_train)
        
        # Make Predictions
        y_train_pred = y_scaler.inverse_transform(model.predict(x_train).reshape(-1,1))
        y_val_pred = y_scaler.inverse_transform(model.predict(x_val).reshape(-1,1))
        y_test_pred = y_scaler.inverse_transform(model.predict(x_test).reshape(-1,1))
        
        # Calculate MAE
        train_mae = mean_absolute_error(y_scaler.inverse_transform(y_train.reshape(-1,1)), y_train_pred)
        val_mae = mean_absolute_error(y_scaler.inverse_transform(y_val.reshape(-1,1)), y_val_pred)
        test_mae = mean_absolute_error(y_scaler.inverse_transform(y_test.reshape(-1,1)), y_test_pred)
        
        # Calculate MAPE
        epsilon = 1e-12  # to avoid division by zero
        train_mape = np.mean(np.abs((y_train - y_train_pred) / (y_train + epsilon))) * 100
        val_mape = np.mean(np.abs((y_val - y_val_pred) / (y_val + epsilon))) * 100
        test_mape = np.mean(np.abs((y_test - y_test_pred) / (y_test + epsilon))) * 100
        
        # Log Metrics in MLflow
        mlflow.log_metric("train_mae", train_mae)
        mlflow.log_metric("val_mae", val_mae)
        mlflow.log_metric("test_mae", test_mae)
        
        mlflow.log_metric("train_mape", train_mape)
        mlflow.log_metric("val_mape", val_mape)
        mlflow.log_metric("test_mape", test_mape)

        
        # Log Model in MLflow
        run = mlflow.active_run()
        artifact_uri = run.info.artifact_uri
        parsed_uri = urllib.parse.urlparse(artifact_uri)
        if parsed_uri.scheme == "file":
            artifact_base_path = Path(parsed_uri.path).resolve()
        else:
            artifact_base_path = Path(parsed_uri.path).resolve()
        metadata_artifact_path = artifact_base_path / "metadata.json"
        wrapper = SklearnRegressorPreprocessWrapper(model, ["name", "description"], one_hot_encoders, multi_hot_encoders, scalers, artifact_base_path)
        metadata = {
            "text_columns": wrapper.text_columns,
            "scaler_paths": wrapper.scaler_paths,
            "onehot_encoder_paths": wrapper.onehot_encoder_paths,
            "multihot_encoder_paths": wrapper.multihot_encoder_paths,
            "model_path": wrapper.model_path,
            "embedding_model_path": wrapper.embedding_model_path
        }
        with open(metadata_artifact_path, "w") as f:
            json.dump(metadata, f)
        
        example_output = wrapper.predict(None, example_input)
        signature = infer_signature(example_input, example_output)
        mlflow.pyfunc.log_model(f"{type(model).__name__}", python_model=wrapper, artifacts={"metadata" : metadata_artifact_path.resolve().as_uri()}, signature=signature, conda_env="env.yaml")

In [8]:
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.linear_model import LinearRegression

for i in [
    LinearRegression(), 
    RandomForestRegressor(n_estimators=300, random_state=42), 
    GradientBoostingRegressor(n_estimators=500, learning_rate=0.02, random_state=42, max_depth=6)
]:
    
    run_sklearn_regressor(i)

/home/erwin/anaconda3/envs/airbnb-demo/lib/python3.10/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
/home/erwin/anaconda3/envs/airbnb-demo/lib/python3.10/site-packages/mlflow/pyfunc/__init__.py:3216: UserWarning: An input example was not provided when logging the model. To ensure the model signature functions correctly, specify the `input_example` parameter. See https://mlflow.org/docs/latest/model/signatures.html#model-input-example for more details about the benefits of using input_example.
  color_warning(
Downloading artifacts: 100%|████████████████████| 1/1 [00:00<00:00, 1839.61it/s]
2025/03/25 23:31:57 WARNING mlflow.utils.requirements_utils: Detected one or more mismatches between the model's dependencies and the current Python environment:
 - numpy (current: 1.26.4, required: numpy==2.2.2)
To fix the mismatches, call `mlflow.pyfunc.get_model_dependencies(model_uri)` to fetch the model's environment and install dependencies using the resulting environment file.
/home/erwin/anaconda3/envs/airbnb-demo/lib/python3.10/site-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/erwin/anaconda3/envs/airbnb-demo/lib/python3.10/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but RandomForestRegressor was fitted without feature names
  warnings.warn(
/home/erwin/anaconda3/envs/airbnb-demo/lib/python3.10/site-packages/mlflow/pyfunc/__init__.py:3216: UserWarning: An input example was not provided when logging the model. To ensure the model signature functions correctly, specify the `input_example` parameter. See https://mlflow.org/docs/latest/model/signatures.html#model-input-example for more details about the benefits of using input_example.
  color_warning(
Downloading artifacts: 100%|████████████████████| 1/1 [00:00<00:00, 1107.55it/s]
2025/03/25 23:32:01 WARNING mlflow.utils.requirements_utils: Detected one or more mismatches between the model's dependencies and the current Python environment:
 - numpy (current: 1.26.4, required: numpy==2.2.2)
To fix the mismatches, call `mlflow.pyfunc.get_model_dependencies(model_uri)` to fetch the model's environment and install dependencies using the resulting environment file.
/home/erwin/anaconda3/envs/airbnb-demo/lib/python3.10/site-packages/sklearn/ensemble/_gb.py:672: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?
/home/erwin/anaconda3/envs/airbnb-demo/lib/python3.10/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but GradientBoostingRegressor was fitted without feature names
  warnings.warn(
/home/erwin/anaconda3/envs/airbnb-demo/lib/python3.10/site-packages/mlflow/pyfunc/__init__.py:3216: UserWarning: An input example was not provided when logging the model. To ensure the model signature functions correctly, specify the `input_example` parameter. See https://mlflow.org/docs/latest/model/signatures.html#model-input-example for more details about the benefits of using input_example.
  color_warning(
Downloading artifacts: 100%|████████████████████| 1/1 [00:00<00:00, 1090.56it/s]
2025/03/25 23:32:04 WARNING mlflow.utils.requirements_utils: Detected one or more mismatches between the model's dependencies and the current Python environment:
 - numpy (current: 1.26.4, required: numpy==2.2.2)
To fix the mismatches, call `mlflow.pyfunc.get_model_dependencies(model_uri)` to fetch the model's environment and install dependencies using the resulting environment file.

### PyTorch MLflow run (with text and description embeddings)

In [9]:
#%pip install torch

In [11]:
import torch.nn.functional as F
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from datetime import datetime
import urllib.parse
from pathlib import Path
import json

# Convert NumPy arrays to PyTorch tensors
x_train, y_train = torch.tensor(x_embedding_train, dtype=torch.float32), torch.tensor(y_train, dtype=torch.float32)
x_val, y_val = torch.tensor(x_embedding_val, dtype=torch.float32), torch.tensor(y_val, dtype=torch.float32)
x_test, y_test = torch.tensor(x_embedding_test, dtype=torch.float32), torch.tensor(y_test, dtype=torch.float32)

# Create PyTorch DataLoaders
batch_size = 64
train_dataset = TensorDataset(x_train, y_train)
val_dataset = TensorDataset(x_val, y_val)
test_dataset = TensorDataset(x_test, y_test)

train_loader = DataLoader(dataset=train_dataset, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(dataset=val_dataset, batch_size=batch_size, shuffle=False)
test_loader = DataLoader(dataset=test_dataset, batch_size=batch_size, shuffle=False)

# Train the model and log with MLflow
input_size = x_embedding_train.shape[1]
num_epochs = 100
learning_rate = 0.001

# Move model to GPU if available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = SimpleNNRegressor(input_size, device=device)
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

model_type_name = type(model).__name__
timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
run_name = f"{model_type_name}_{timestamp}"

with mlflow.start_run(run_name=run_name):
    mlflow.log_param("dataset_version", dataset_version)
    mlflow.log_param("input_size", input_size)
    mlflow.log_param("learning_rate", learning_rate)
    mlflow.log_param("num_epochs", num_epochs)
    
    # Define the learning rate scheduler
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=3, min_lr=1e-6, verbose=True)
    
    # Training Loop
    for epoch in range(num_epochs):
        total_loss = 0
        
        model.train()
        for features, labels in train_loader:
            features, labels = features.to(device), labels.to(device).view(-1, 1)
            optimizer.zero_grad()
            outputs = model(features)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
        
        train_loss = total_loss / len(train_loader)
        mlflow.log_metric("train_loss", train_loss, step=epoch)
        print(f"Epoch [{epoch+1}/{num_epochs}], Train Loss: {train_loss:.4f}")
    
        # Evaluate Model on Validation Set
        model.eval()
        total_loss = 0
        
        with torch.no_grad():
            for features, labels in val_loader:
                features, labels = features.to(device), labels.to(device).view(-1, 1)
                outputs = model(features)
                loss = criterion(outputs, labels)
                total_loss += loss.item()
        
        val_loss = total_loss / len(val_loader)
        mlflow.log_metric("val_loss", val_loss, step=epoch)
        print(f"Validation Loss: {val_loss:.4f}")
        
        # Adjust learning rate based on validation loss
        scheduler.step(val_loss)
    
    # Evaluate Model on Test Set
    model.eval()
    total_loss = 0
    total_mae = 0
    total_mape = 0
    n_batches = 0
    
    with torch.no_grad():
        for features, labels in test_loader:
            features, labels = features.to(device), labels.to(device).view(-1, 1)

            outputs = model(features)
            scaled_outputs = torch.tensor(y_scaler.inverse_transform(outputs.cpu()))
            scaled_labels = torch.tensor(y_scaler.inverse_transform(labels.cpu()))
            loss = criterion(outputs, labels)
            mae = F.l1_loss(scaled_outputs, scaled_labels)
            epsilon = 1e-8
            percentage_errors = torch.abs((scaled_outputs - scaled_labels) / (scaled_labels + epsilon)) * 100
            mape = percentage_errors.mean()
    
            total_loss += loss.item()
            total_mae += mae.item()
            total_mape += mape.item()
            n_batches += 1
    
    test_loss = total_loss / n_batches
    test_mae = total_mae / n_batches
    test_mape = total_mape / n_batches
    
    mlflow.log_metric("test_loss", test_loss)
    mlflow.log_metric("test_mae", test_mae)
    mlflow.log_metric("test_mape", test_mape)
    
        
    # Log Model in MLflow
    run = mlflow.active_run()
    artifact_uri = run.info.artifact_uri
    parsed_uri = urllib.parse.urlparse(artifact_uri)
    if parsed_uri.scheme == "file":
        artifact_base_path = Path(parsed_uri.path).resolve()
    else:
        artifact_base_path = Path(parsed_uri.path).resolve()
    metadata_artifact_path = artifact_base_path / "metadata.json"
    wrapper = TorchNNPreprocessWrapper(model, ["name", "description"], one_hot_encoders, multi_hot_encoders, embedding_model_path, scalers, artifact_base_path)
    metadata = {
        "text_columns": wrapper.text_columns,
        "scaler_paths": wrapper.scaler_paths,
        "onehot_encoder_paths": wrapper.onehot_encoder_paths,
        "multihot_encoder_paths": wrapper.multihot_encoder_paths,
        "model_path": wrapper.model_path,
        "embedding_model_path": wrapper.embedding_model_path
    }

    with open(metadata_artifact_path, "w") as f:
        json.dump(metadata, f)
    
    example_output = wrapper.predict(None, example_input)
    signature = infer_signature(example_input, example_output)
    mlflow.pyfunc.log_model("neural_network", python_model=wrapper, artifacts={"metadata" : metadata_artifact_path.resolve().as_uri()}, signature=signature, conda_env="env.yaml", input_example=example_input)

/tmp/ipykernel_20515/2301055071.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x_train, y_train = torch.tensor(x_embedding_train, dtype=torch.float32), torch.tensor(y_train, dtype=torch.float32)
/tmp/ipykernel_20515/2301055071.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x_val, y_val = torch.tensor(x_embedding_val, dtype=torch.float32), torch.tensor(y_val, dtype=torch.float32)
/tmp/ipykernel_20515/2301055071.py:14: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x_test, y_test = torch.tensor(x_embedding_test, dtype=torch.float32), torch.tensor(y_test, dtype=torch.float32)
/home/erwin/anaconda3/envs/airbnb-demo/lib/python3.10/site-packages/torch/optim/lr_scheduler.py:62: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Epoch [1/100], Train Loss: 0.0169
Validation Loss: 0.0147
Epoch [2/100], Train Loss: 0.0120
Validation Loss: 0.0136
Epoch [3/100], Train Loss: 0.0110
Validation Loss: 0.0125
Epoch [4/100], Train Loss: 0.0098
Validation Loss: 0.0131
Epoch [5/100], Train Loss: 0.0086
Validation Loss: 0.0134
Epoch [6/100], Train Loss: 0.0068
Validation Loss: 0.0147
Epoch [7/100], Train Loss: 0.0057
Validation Loss: 0.0140
Epoch [8/100], Train Loss: 0.0038
Validation Loss: 0.0129
Epoch [9/100], Train Loss: 0.0026
Validation Loss: 0.0141
Epoch [10/100], Train Loss: 0.0019
Validation Loss: 0.0127
Epoch [11/100], Train Loss: 0.0015
Validation Loss: 0.0131
Epoch [12/100], Train Loss: 0.0010
Validation Loss: 0.0129
Epoch [13/100], Train Loss: 0.0007
Validation Loss: 0.0129
Epoch [14/100], Train Loss: 0.0006
Validation Loss: 0.0130
Epoch [15/100], Train Loss: 0.0005
Validation Loss: 0.0131
Epoch [16/100], Train Loss: 0.0004
Validation Loss: 0.0131
Epoch [17/100], Train Loss: 0.0003
Validation Loss: 0.0131
Epoch [18/100], Train Loss: 0.0003
Validation Loss: 0.0132
Epoch [19/100], Train Loss: 0.0003
Validation Loss: 0.0133
Epoch [20/100], Train Loss: 0.0002
Validation Loss: 0.0133
Epoch [21/100], Train Loss: 0.0002
Validation Loss: 0.0133
Epoch [22/100], Train Loss: 0.0002
Validation Loss: 0.0133
Epoch [23/100], Train Loss: 0.0002
Validation Loss: 0.0133
Epoch [24/100], Train Loss: 0.0002
Validation Loss: 0.0133
Epoch [25/100], Train Loss: 0.0002
Validation Loss: 0.0134
Epoch [26/100], Train Loss: 0.0002
Validation Loss: 0.0133
Epoch [27/100], Train Loss: 0.0002
Validation Loss: 0.0134
Epoch [28/100], Train Loss: 0.0002
Validation Loss: 0.0134
Epoch [29/100], Train Loss: 0.0002
Validation Loss: 0.0134
Epoch [30/100], Train Loss: 0.0002
Validation Loss: 0.0134
Epoch [31/100], Train Loss: 0.0002
Validation Loss: 0.0134
Epoch [32/100], Train Loss: 0.0002
Validation Loss: 0.0134
Epoch [33/100], Train Loss: 0.0002
Validation Loss: 0.0134
Epoch [34/100], Train Loss: 0.0002
Validation Loss: 0.0134
Epoch [35/100], Train Loss: 0.0002
Validation Loss: 0.0134
Epoch [36/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [37/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [38/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [39/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [40/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [41/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [42/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [43/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [44/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [45/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [46/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [47/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [48/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [49/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [50/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [51/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [52/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [53/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [54/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [55/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [56/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [57/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [58/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [59/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [60/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [61/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [62/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [63/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [64/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [65/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [66/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [67/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [68/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [69/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [70/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [71/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [72/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [73/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [74/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [75/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [76/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [77/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [78/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [79/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [80/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [81/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [82/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [83/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [84/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [85/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [86/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [87/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [88/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [89/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [90/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [91/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [92/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [93/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [94/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [95/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [96/100], Train Loss: 0.0001
Validation Loss: 0.0135
Epoch [97/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [98/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [99/100], Train Loss: 0.0001
Validation Loss: 0.0134
Epoch [100/100], Train Loss: 0.0001
Validation Loss: 0.0134

2025/03/25 23:36:11 INFO mlflow.pyfunc: Validating input example against model signature
Downloading artifacts: 100%|████████████████████| 1/1 [00:00<00:00, 1589.96it/s]
2025/03/25 23:36:11 WARNING mlflow.utils.requirements_utils: Detected one or more mismatches between the model's dependencies and the current Python environment:
 - numpy (current: 1.26.4, required: numpy==2.2.2)
To fix the mismatches, call `mlflow.pyfunc.get_model_dependencies(model_uri)` to fetch the model's environment and install dependencies using the resulting environment file.
2025/03/25 23:36:11 WARNING mlflow.utils.requirements_utils: Detected one or more mismatches between the model's dependencies and the current Python environment:
 - numpy (current: 1.26.4, required: numpy==2.2.2)
To fix the mismatches, call `mlflow.pyfunc.get_model_dependencies(model_uri)` to fetch the model's environment and install dependencies using the resulting environment file.
/home/erwin/Desktop/airbnb-demo/models.py:222: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.model = torch.load(path)
2025/03/25 23:36:11 WARNING mlflow.models.model: Failed to validate serving input example {
  "dataframe_split": {
    "columns": [
      "name",
      "description",
      "accommodates",
      "bathrooms",
      "bedrooms",
      "beds",
      "availability_365",
      "review_scores_value"
    ],
    "data": [
      [
        "Triple Room With City View",
        "This tastefully decorated room has an elegant interior with vintage color accents. The modern walk-in shower has a rain shower head.",
        -6.873799989987651,
        -52.03059398428852,
        -8.755921521207384,
        -3.6465830840431614,
        -1.2026649485212029,
        -865.9527974481216
      ]
    ]
  }
}. Alternatively, you can avoid passing input example and pass model signature instead when logging the model. To ensure the input example is valid prior to serving, please try calling `mlflow.models.validate_serving_input` on the model uri and serving input example. A serving input example can be generated from model input example using `mlflow.models.convert_input_example_to_serving_input` function.
Got error: Invalid magic number; corrupt file?